import { Equipment } from '../_models/equipment';

export const INITIAL_EQUIPMENT_MAP: Record<string, Equipment> = {
  path7895: new Equipment('kkd-11', 'Crusher', 'OFF', 'crusher', new Date()),
  path7072: new Equipment('bunk-1', 'Bunker', 'OFF', 'bunker', new Date()),
  'path7895-4-7': new Equipment(
    'krd-12',
    'Crusher',
    'OFF',
    'crusher',
    new Date(),
  ),
  'path7895-4-4': new Equipment(
    'krd-13',
    'Crusher',
    'OFF',
    'crusher',
    new Date(),
  ),
  'path6910-8': new Equipment('bunk-2', 'Bunker', 'OFF', 'bunker', new Date()),
  'K-2-1': new Equipment('conv-k-2', 'Conveyor', 'OFF', 'conveyor', new Date()),
  'K-1-1': new Equipment('conv-k-1', 'Conveyor', 'OFF', 'conveyor', new Date()),
  'M-2-1': new Equipment('conv-m-2', 'Conveyor', 'OFF', 'conveyor', new Date()),
  'M-1-1': new Equipment('conv-m-1', 'Conveyor', 'OFF', 'conveyor', new Date()),
  'path6910-8-6-6': new Equipment(
    'bunk-3',
    'Bunker',
    'OFF',
    'bunker',
    new Date(),
  ),
  'path7054-0-9': new Equipment(
    'ksd-3',
    'Crusher',
    'OFF',
    'crusher',
    new Date(),
  ),
  'path7054-0-9-23': new Equipment(
    'kmd-3',
    'Crusher',
    'OFF',
    'crusher',
    new Date(),
  ),
  'path7054-0': new Equipment('ksd-4', 'Crusher', 'OFF', 'crusher', new Date()),
  'path7054-0-9-64': new Equipment(
    'kmd-4',
    'Crusher',
    'OFF',
    'crusher',
    new Date(),
  ),
  'path7054-0-9-6': new Equipment(
    'ksd-5',
    'Crusher',
    'OFF',
    'crusher',
    new Date(),
  ),
  'path7054-0-9-7': new Equipment(
    'kmd-5',
    'Crusher',
    'OFF',
    'crusher',
    new Date(),
  ),
  'path7054-0-9-8': new Equipment(
    'ksd-6',
    'Crusher',
    'OFF',
    'crusher',
    new Date(),
  ),
  'path7054-0-9-38': new Equipment(
    'kmd-6',
    'Crusher',
    'OFF',
    'crusher',
    new Date(),
  ),
  'M-15': new Equipment('conv-m-15', 'Conveyor', 'OFF', 'conveyor', new Date()),
};
